### ISSUE TITLE
Allow for Clients to Pass in a Transform Function to Extract Existing Offsets from Cursors

### ISSUE THREAD

**Issue by darthtrevino** [darthtrevino/relay-cursor-paging#2]
If the cursors contain Node IDs that are auto-incremented in ascending order, the function works fine. However, if you apply a criteria or sort order that makes identifiers not appear in ascending order, this will break paging functionality. In these cases the result order should be packed into node cursors by clients. Clients would then pass in a transform function to unpack those offsets so we could determine where in the result set to start.

**Comment by darthtrevino** [comment]
Derp. The cursor we're unpacking is based on the ArrayConnection:<index> cursor generated by edges. This is a non-issue.

**Comment by elasticsearcher** [comment]
@darthtrevino Thanks for this clarification! I was puzzled by this seemingly glaring issue, i.e. offsets shouldn't be ID-based as it seems to be the case in the code at first glance, but in reality we are dealing with indexes within an ArrayConnection, which comes from connectionFromArraySlice, and this correctly translates to how LIMIT works in SQL.
